spring:
  application:
    name: pdf-generator

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /pdf-generator

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${AWS_S3_BUCKET:emisnet-pdf-storage}

# Logging Configuration
logging:
  level:
    com.bmv.emisnet.pdfgenerator: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# PDF Generation Configuration
pdf:
  generator:
    default-font: "Arial"
    default-font-size: 12
    page-size: "A4"
    margins:
      top: 20
      bottom: 20
      left: 20
      right: 20
