spring:
  application:
    name: pdf-generator

server:
  port: 8080
  servlet:
    context-path: /pdf-generator

logging:
  level:
    com.bmv.emisnet.pdfgenerator: INFO
    org.springframework: WARN